### ISSUE TITLE
Record email opt-in in Mailchimp?

### ISSUE THREAD

**Issue by stedall** [strangerstudios/pmpro-mailchimp#97] opened 2020-03-09 19:17 UTC
WP 5.3.2/pmpro 2.2.6/pmpro-mailchimp 2.2.1

I am not completely sure if this relates to this plugin or to Mailchimp, but if a user selects a mailing list during membership signup, they receive confirmation email and are then added to Mailchimp, but when you view that user in Mailchimp, under GDPR, the user is not marked as Opted-In. The user can change their preferences from the sign-up email, but by default, Email doesn't seem to be set.

Is this intentional? It doesn't completely make sense to me. Or is there any way to have the user show as opted in by passing an additional field to Mailchimp?

**Comment by dparker1005** [comment] 2020-09-18 15:33
Hello,

PMPro Mailchimp does not currently update Mailchimp's GDPR consent fields, though we have another issue in this repository noting that potential improvement  here: https://github.com/strangerstudios/pmpro-mailchimp/issues/47

If you have further questions about this, please feel free to follow up on that original issue.

**Comment by dparker1005** [comment] 2021-02-17 19:44
I am now closing this issue as it is a duplicate of #47.

**Closed by dparker1005** 2021-02-17 19:44 UTC
